services:
  - type: web
    name: military-asset-backend
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: http://localhost:5173,https://military-asset-mgmt-system-kristalb.vercel.app
      - key: MONGO_URI
        fromSecret: MONGO_URI